### ISSUE TITLE
Visual Glossary: revision to the title of the section "Positioning"

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPoseGuides#48]
During the September 3 meeting we discussed the merits of the title "Positioning" for the section that provides definitions for local, global and universal positioning systems. 

the term “Geodesy” has been proposed but Mikel feels is insufficient to cover all the scope. Is there a better term?

What about calling the Positioning Systems to “Spatial Reference Systems”? Not really. 

Mikel proposes to add an introduction to the Positioning section to include/explain how the terms in the group are related to the idea of geodetic systems and include Spatial Reference Systems. Also be perfectly clear about how this section is NOT about GPS (the technology)

**Comment by lieberjosh** [comment]
Spatial referencing is more consonant with ISO terminology. The reference systems are how to do spatial referencing by coordinates.

**Comment by MikelSalazar** [comment]
Thank you, Josh. i would like to keep it simple... but if you can share with me the specific ISO documents so that I can review this topic, I'll be open to change it.

**Comment by cperey** [comment]
Done.
